Internal Server Error: /
Traceback (most recent call last):
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 202, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_session

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/martsime/OneDrive - NTNU/Skole/4.Semester/TDT4140 - Programvareutvikling/prosjekt/TDT4140-NIDALA/nidala/views.py", line 4, in index
    return render(request, 'nidala/index.html')
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/defaulttags.py", line 308, in render
    match = condition.eval(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/defaulttags.py", line 868, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 711, in resolve
    obj = self.var.resolve(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 852, in resolve
    value = self._resolve_lookup(context)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/utils/functional.py", line 234, in inner
    self._setup()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/utils/functional.py", line 380, in _setup
    self._wrapped = self._setupfunc()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 180, in get_user
    user_id = _get_user_session_key(request)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 57, in __getitem__
    return self._session[key]
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
    self._session_cache = self.load()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 35, in load
    expire_date__gt=timezone.now()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/martsime/.virtualenvs/nidala/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 337, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_session
"GET / HTTP/1.1" 500 257327
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3523
"GET / HTTP/1.1" 200 3128
"GET /static/css/base.css HTTP/1.1" 304 0
"GET / HTTP/1.1" 200 3128
"GET /static/css/base.css HTTP/1.1" 200 1064
"GET /static/css/bootstrap.min.css HTTP/1.1" 200 144024
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3523
